#pragma once

template <class T>
class CProxy_IApp2Events : 
	public IConnectionPointImpl<T, &__uuidof( _IApp2Events ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
