#pragma once

template <class T>
class CProxy_IRecordEvents : public IConnectionPointImpl<T, &__uuidof( _IRecordEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
