mkdir "%LOCALAPPDATA%\Felix\html\"
mkdir "%LOCALAPPDATA%\Felix\html\jp\"
mkdir "%LOCALAPPDATA%\Felix\html\en\"
mkdir "%LOCALAPPDATA%\Felix\html\jp\manager\"
mkdir "%LOCALAPPDATA%\Felix\html\en\manager\"
mkdir "%LOCALAPPDATA%\Felix\html\js\"
mkdir "%LOCALAPPDATA%\Felix\html\images\"
copy "C:\dev\cpp\Assistant Suite\Felix\html\*.css"               "%LOCALAPPDATA%\Felix\html\"
copy "C:\dev\cpp\Assistant Suite\Felix\html\jp\*"                "%LOCALAPPDATA%\Felix\html\jp\"
copy "C:\dev\cpp\Assistant Suite\Felix\html\en\*"               "%LOCALAPPDATA%\Felix\html\en\"
copy "C:\dev\cpp\Assistant Suite\Felix\html\jp\manager\*" "%LOCALAPPDATA%\Felix\html\jp\manager\"
copy "C:\dev\cpp\Assistant Suite\Felix\html\en\manager\*" "%LOCALAPPDATA%\Felix\html\en\manager\"
copy "C:\dev\cpp\Assistant Suite\Felix\html\js\*"                "%LOCALAPPDATA%\Felix\html\js\"
copy "C:\dev\cpp\Assistant Suite\Felix\html\images\*"        "%LOCALAPPDATA%\Felix\html\images\"