//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FelixENG.rc
//
#define IDS_LANG_CODE                   3
#define IDS_LANG_STRING                 4
#define IDS_OPEN_TOOLBAR                5
#define IDS_SAVE_TOOLBAR                6
#define IDS_SAVE_MANY_TOOLBAR           7
#define IDS_SEARCH_TOOLBAR              9
#define IDS_GLOSSARY_MANAGER_TITLE      10
#define IDS_MERGE_MEM_TITLE             11
#define IDS_MERGE_GLOSS_TITLE           12
#define IDS_MERGE_MEM_TEXT              13
#define IDS_MERGE_GLOSS_TEXT            14
#define IDS_REFLECTED_TRANS             15
#define IDS_BATCH_VALIDATE              16
#define IDS_SHOW_TRANS                  16
#define IDS_DELETE_TITLE                17
#define IDS_LOCK                        18
#define IDS_LOAD_PREFS_TITLE            18
#define IDS_ADD2GLOSS_TITLE             19
#define IDS_PROJNAME                    20
#define IDS_PREFERENCES_TITLE           21
#define IDS_PDF_HELPFILE_NAME           22
#define IDS_ONLINE_HELPFILE_URL         23
#define IDS_START_EDIT                  24
#define IDS_END_EDIT                    25
#define IDD_ABOUTBOX                    26
#define IDS_SAVE_PREFS_TITLE            26
#define IDS_EDIT_STRINGS                27
#define IDD_CONCORDANCE                 28
#define IDS_SEND_BTN                    29
#define IDS_DONT_SEND_BTN               30
#define IDS_CRASH_PAGE                  31
#define IDD_FIND_DIALOG                 32
#define IDS_PREFS_SAVED                 32
#define IDD_FIND_DLG                    33
#define IDS_STRING33                    33
#define IDS_PREFS_LOADED                33
#define IDR_FORMAT_TOOLBAR              34
#define IDS_TRANS_REVIE_FAILED          34
#define IDS_TRANS_REVIEW_FAILED         34
#define IDS_REGISTER_TITLE              35
#define IDS_SET_SOURCE_TITLE            36
#define IDS_SET_TRANS_TITLE             37
#define IDS_ABOUT_TITLE                 38
#define IDS_MORE_TITLE                  39
#define IDS_LESS_TITLE                  40
#define IDS_TO_ACTIVATE_TITLE           41
#define IDS_BACK_TITLE                  42
#define IDS_ADD2MEM_TITLE               43
#define IDS_DONE                        44
#define IDS_GETTING_LANG_CODES          45
#define IDS_MINCHO                      46
#define IDI_ICON2                       47
#define IDS_CONNECTED_MEMORY            47
#define IDD_EDIT_FIND_DIALOG            48
#define IDS_DELETED_RECORD_MSG          48
#define IDD_ADVANCED_MEM_MGR_DLG        49
#define IDS_DELETE_FAILED_MEM_LOCKED_MSG 49
#define IDD_ADD_STRING_DLG              50
#define IDS_REPLACE_COMPLETE_MSG        50
#define IDD_USER_STRING_DLG             51
#define IDS_SEARCHWIN_TITLE_MEM         51
#define IDB_NETWORK                     52
#define IDS_SEARCHWIN_TITLE_GLOSS       52
#define IDD_PROPPAGE_ALGORITHM          53
#define IDS_POPUP_COPY                  53
#define IDB_SAVE_PREFS                  53
#define IDS_RETRIEVING_LANG_CODES       54
#define IDB_OPEN_PREFS                  54
#define IDD_SELECT_LANG_DLG             55
#define IDS_POPUP_SWITCH_VIEWS          55
#define IDS_IMPORT_COMPLETE             56
#define IDS_DEFAULT_ID2                 57
#define IDS_PREV                        58
#define IDS_NEXT                        59
#define IDS_ADD_TO_MEMORY               60
#define IDS_ADD_TO_GLOSS                61
#define IDS_MORE                        62
#define IDS_SET_SOURCE                  63
#define IDS_SET_TRANS                   64
#define IDS_SET_GLOSS                   65
#define IDS_BACK                        66
#define IDS_REGISTER                    67
#define IDS_SHOW_HELP_FAILED            68
#define IDS_ERROR_TITLE                 69
#define IDS_FOUND_1_MATCH               70
#define IDS_FOUND_X_MATCHES             71
#define IDS_REG_KEY                     72
#define IDS_SOURCE_ID                   73
#define IDS_TRANS_ID                    74
#define IDS_CONTEXT_ID                  75
#define IDS_VALIDATED_ID                76
#define IDS_RELIABILITY_ID              77
#define IDS_CREATED_ID                  78
#define IDS_MODIFIED_ID                 79
#define IDS_QUERY_ID                    80
#define IDS_DUMMY_QUERY_ID              81
#define IDS_DUMMY_SOURCE_ID             82
#define IDS_DUMMY_TRANS_ID              83
#define IDS_RICH_QUERY_ID               84
#define IDS_RICH_SOURCE_ID              85
#define IDS_MSG_INVALID_COMMAND         86
#define IDS_MULTITERM_EXPORT_TITLE      87
#define IDS_MULTITERM_IMPORT_TITLE      88
#define IDS_SELECT_LANGUAGE             89
#define IDS_EXPORT_DESTINATION          90
#define IDS_OPEN                        91
#define IDS_NOT_UNICODE_FILE            92
#define IDS_MSG_S_T_MUST_DIFFER         93
#define IDS_MSG_EXPORT_FAILED           94
#define IDS_MSG_EXPORTING_RECORDS       95
#define IDS_MSG_IMPORTING_GLOSSARY      96
#define IDS_MSG_ACTION_CANCELLED        97
#define IDS_MSG_ACTION_FAILED           98
#define IDS_SEARCH_RESULTS              99
#define IDS_CURRENT_SIZE                100
#define IDS_DELETED_ENTRY               101
#define IDS_GLOSSARY                    102
#define IDS_MEMORY                      103
#define IDS_PROMPT_OVERWRITE_MEMORY     104
#define IDS_PROMPT_OVERWRITE_MEMORY_TITLE 105
#define IDS_ENTERING_EDIT_MODE          106
#define IDS_IN_EDIT_MODE                107
#define IDS_LEAVING_EDIT_MODE           108
#define IDS_LEFT_EDIT_MODE              109
#define IDS_POST_EDIT_ALL_DELETED       110
#define IDS_NO_TRANS_SELECTED           111
#define IDD_GLOSSARYVIEW                112
#define IDS_POPUP_ADD_TO_GLOSS          112
#define IDS_NO_SOURCE_SELECTED          113
#define IDS_GLOSS_SEARCH                114
#define IDS_MEMORY_SEARCH               115
#define IDD_CONCORDANCE_DIALOG          116
#define IDS_NO_SOURCE_SELECTED_RICH     116
#define IDD_PROPPAGE_MEMORY             117
#define IDS_NO_TRANS_SELECTED_RICH      117
#define IDS_REG_KEY_GLOSS               118
#define IDS_EDIT_COMPLETE               119
#define IDS_MSG_DROPPED_RECORDS         120
#define IDD_DELETE                      121
#define IDC_DELETE                      122
#define IDC_CHECK_DEMO                  123
#define IDS_IDS_REG_LINK_DEAD           123
#define IDC_EDIT_ACCELERATORS           124
#define IDS_POPUP_REGISTER_GLOSS        124
#define IDC_SOURCE_EDIT                 125
#define IDS_POPUP_DELETE                125
#define IDD_EDIT_ENTRY                  126
#define IDC_REGISTER                    127
#define IDR_MAINFRAME                   128
#define IDC_ADD_TO_GLOSSARY             129
#define IDC_TRANS_EDIT                  130
#define IDS_QUERY_NATIVE                130
#define IDC_RELIABILITY_EDIT            131
#define IDS_DEFAULT_ID3                 132
#define IDS_MSG_DROPPED_RECORDS_TITLE   133
#define IDS_MSG_REGISTERED_SERVER       134
#define IDC_CONTEXT_EDIT                135
#define IDC_TOGGLE_MARK                 135
#define IDC_BOLD                        136
#define IDS_REG_GLOSS_ENTRY             136
#define IDC_VALIDATED_CHECK             137
#define IDC_TOGGLE_MARK_ON              137
#define IDC_CREATED_BOX                 138
#define IDC_TOGGLE_MARK_OFF             138
#define IDC_MODIFIED_BOX                139
#define IDS_TOGGLE_TITLE                139
#define IDC_SEARCH                      140
#define IDS_SELECT_SOURCE_TRANS         140
#define IDC_VALIDATED_CHECK2            140
#define IDC_REPLACE                     141
#define IDS_SELECT_CONTEXT_AND_DESTINATION 141
#define IDC_EDIT                        142
#define IDC_ALIGN_SOURCE                143
#define IDS_SELECT_VAL_AND_REL          143
#define IDC_ALIGN_TARGET                144
#define IDS_ADD_TO_GLOSS_ACTIVE         144
#define IDC_DELETE_SOURCE               145
#define IDC_DELETE_TARGET               146
#define IDC_CRASH_ONE                   147
#define IDS_ADD_TO_GLOSS_DEAD           147
#define IDC_CRASH_TWO                   148
#define IDS_CORRUPT_FILE                148
#define IDC_REPLACE_ALL                 149
#define IDC_SOURCE_COMBO                150
#define IDC_TRANS_COMBO                 151
#define IDC_NAV                         152
#define IDC_PREV                        153
#define IDC_NEXT                        154
#define IDC_LESS                        155
#define IDC_CMD                         156
#define IDC_ABOUT                       157
#define IDC_ADD                         158
#define IDC_MORE                        159
#define IDC_SET_SOURCE                  160
#define IDC_SET_TRANS                   161
#define IDC_SET_GLOSS                   162
#define IDD_PROPSHEET                   163
#define IDC_AUTOMATION_SAVE             164
#define IDS_LESS                        165
#define IDR_APPLICATION2                166
#define IDC_REMOVE_GLOSSARY             167
#define IDC_ADD_RECORD_FROM_GLOSSARY    168
#define IDC_CHECK_LOCATIONS             169
#define IDR_ICON                        170
#define IDR_APPLICATION                 171
#define IDC_IGNORE_CASE_CHECK           172
#define IDS_MSG_REGISTERED_SERVER_TITLE 173
#define IDS_MSG_RECORD_CREATION_FAILED  174
#define IDS_OPEN_GLOSS_FILE             175
#define IDC_REPLACE_EDIT_RECORD         177
#define SIDEBAR_ID                      178
#define IDR_RECORD                      179
#define IDR_MEMORY                      180
#define IDR_MEMORIES                    181
#define IDR_GLOSSARYWINDOW              182
#define IDR_GLOSSARYWINDOWS             183
#define IDC_REGEX_CHECK                 184
#define IDC_LIST                        185
#define IDD_MEM_MGR_DLG                 186
#define IDC_INFO_BOX                    187
#define IDC_UP                          188
#define IDC_DOWN                        189
#define IDC_ADD_MEMORY                  190
#define IDC_REMOVE_MEMORY               191
#define IDC_EDIT_MEMORY                 192
#define IDC_MIN_VIEW_BEGIN              193
#define IDC_MIN_VIEW_END                194
#define IDR_PROPERTIES                  195
#define IDR_MEMORYPROPERTIES            196
#define IDR_GLOSSARYPROPERTIES          197
#define IDR_GENERALPROPERTIES           198
#define IDC_MEMSIZE_FULL                199
#define IDC_MEMSIZE_MEDIUM              200
#define IDC_MEMSIZE_MIN                 201
#define IDC_IGNORE_WIDTH_CHECK          202
#define IDD_REG_GLOSS_WIZPAGE_1         202
#define IDC_DEMO_CHECK_EXCESS           203
#define IDC_SOURCE_BOX                  204
#define IDC_TRANS_BOX                   205
#define IDC_CONTEXT_BOX                 206
#define IDC_SOURCE_BOX2                 206
#define IDC_ONLY_VALIDATED_CHECK        207
#define IDC_TRANS_BOX2                  207
#define IDC_FIND_IGNORE_WIDTH_CHECK     208
#define IDC_FIND_IGNORE_HIR_KAT_CHECK   209
#define IDC_MIN_MATCH_SPIN              210
#define IDC_MIN_MATCH_EDIT              211
#define IDR_GLOSSARYMENU                212
#define IDC_MIN_MATCH_STATIC            213
#define IDB_SAVEMANY                    213
#define IDC_MAX_ADD_EDIT                214
#define IDB_SAVE                        214
#define IDC_PLAINTEXT_CHECK             215
#define IDC_MAX_ADD_SPIN                216
#define IDC_GLOSS_TO_LOWER_CHECK        217
#define IDC_GLOSS_PLAINTEXT_CHECK       218
#define IDD_INPUT_SYMBOL_DLG            219
#define IDC_GLOSS_IGNORE_CASE_CHECK     220
#define IDB_PASTE                       220
#define IDC_MIN_MATCH_STATIC2           221
#define IDS_EDIT_RECORD_TITLE           222
#define IDS_MSG_NO_EMPTY_S_OR_T         223
#define IDC_MULTI55                     224
#define IDC_FUZZY_EDIT                  225
#define IDB_OPEN                        225
#define IDS_MSG_EDIT_REC_FAILED         226
#define IDS_MODIFIED                    227
#define IDC_MULTI6                      228
#define IDC_FUZZY_SPIN                  229
#define IDB_NEW_DOCUMENT                229
#define IDS_CREATED                     230
#define IDS_MSG_NO_FILE                 231
#define IDC_FILENAME_EDIT               232
#define IDD_IMPORT_DIALOG               233
#define IDC_MIN_MATCH_STATIC3           235
#define IDD_EDIT_RECORD                 236
#define IDC_BROWSE_BTN                  237
#define IDD_MULTITERM_CONVERSION_DLG    239
#define IDD_NAG_BOX                     240
#define IDD_INPUT_KEY_DLG               241
#define IDC_FILENAME_STATIC             242
#define IDC_VERSION_STATIC              243
#define IDB_COPY                        243
#define IDR_REGISTERMENU                244
#define IDC_RELIABILITY_SPIN            246
#define IDC_ABOUT_MSG_BOX               247
#define IDC_NAG_MSG_BOX                 248
#define IDC_KEY_EDIT                    249
#define IDC_SOURCE_STATIC               250
#define IDC_TRANS_STATIC                251
#define IDC_CONTEXT_STATIC              252
#define IDC_SOURCE_GLOSS_STATIC         252
#define IDC_RELIABILITY_STATIC          253
#define IDC_TRANS_GLOSS_STATIC          253
#define IDC_FORMATTING_CHECK            254
#define IDC_PROGRESS_BAR                255
#define IDD_HELP_DLG                    256
#define IDR_HELP_MENU                   257
#define IDD_EDIT_MODE_FIND_DLG          258
#define IDD_EDIT_MODE_REPLACE_DLG       259
#define IDD_EDIT_MODE_REPLACE_DIALOG    260
#define IDC_ALGO_CHAR                   261
#define IDC_ALGO_WORD                   262
#define IDC_EDIT_BOX                    263
#define IDC_ALGO_CHAR2                  263
#define IDC_ALGO_AUTO                   263
#define IDC_LOCKED                      264
#define IDB_CUT                         264
#define IDI_ICON1                       265
#define IDB_DELETE                      265
#define IDI_ICON3                       266
#define IDS_SEARCH_TOOLBAR_GLOSS        267
#define IDB_BITMAP2                     268
#define IDS_MSG_FINISHED_MULTITERM_EXPORT 269
#define IDB_FONT                        269
#define IDD_MIN_VIEW_DLG                270
#define IDB_HELP                        270
#define IDS_MSG_LOADING                 271
#define IDB_PROPERTIES                  271
#define IDC_VALIDITY                    272
#define IDB_SEARCH                      272
#define IDD_PROPPAGE_VIEW               273
#define IDB_MEM_MGR                     273
#define IDC_ALGO_CHAR_GLOSS             274
#define IDD_PROPPAGE_GENERAL            274
#define IDS_PROMPT_RESCUE_ENTRIES       275
#define IDD_REG_GLOSS_WIZPAGE_2         275
#define IDS_LOAD_FAILED                 276
#define IDD_REG_GLOSS_WIZPAGE_3         276
#define IDC_MIN_BUTTON                  277
#define IDD_ADD_GLOSS                   277
#define IDC_ALGO_WORD_GLOSS             278
#define IDC_EDIT_STRINGS                279
#define IDC_ADD_STRING                  280
#define IDC_EXTRA_STRING_BOX            281
#define IDC_USER_STRINGS                282
#define IDC_IGNORE_HIR_KAT_CHECK        283
#define IDC_GLOSS_IGNORE_WIDTH_CHECK    284
#define IDC_GLOSS_IGNORE_HIR_KAT_CHECK  285
#define IDC_TABBED_VIEW                 286
#define IDC_ONE_SCREEN_MATCH            287
#define IDC_BACK_COLOR_BOX              288
#define IDC_BACK_BTN                    289
#define IDS_MSG_ADDED_RECORDS           290
#define IDS_MSG_ADDED_GLOSS_ENTRY_TITLE 291
#define IDC_QUERY_COLOR_BOX             292
#define IDC_BATCH_STATIC                293
#define IDB_INFORMATION                 293
#define IDS_SOURCE_TITLE                294
#define IDS_TRANS_TITLE                 295
#define IDC_SOURCE_COLOR_BOX            296
#define IDC_CONCORDANCE_EDIT            297
#define IDS_CONTEXT_TITLE               298
#define IDS_QUERY_TITLE                 299
#define IDC_TRANS_COLOR_BOX             300
#define IDC_FIELD_STATIC                301
#define IDS_NO_CONTEXT                  302
#define IDS_MSG_LOADED_RECORDS          303
#define IDC_QUERY_BTN                   304
#define IDC_CONCORDANCE_STATIC          305
#define IDS_MAIN                        306
#define IDS_OUT_OF_RANGE                307
#define IDC_SOURCE_BTN                  308
#define IDC_TARGET_STATIC               309
#define IDC_TARGET_LANG_STATIC          309
#define IDS_EDIT_GLOSS                  310
#define IDS_PROMPT_DELETE               311
#define IDC_TRANS_BTN                   312
#define IDC_LANG_COMBO_SOURCE           313
#define IDC_LANG_COMBO_TRANS            314
#define IDC_LANG_STATIC_SOURCE          315
#define IDC_LANG_COMBO_TRANS2           315
#define IDC_LANG_TRANS_COMBO            315
#define IDC_LANG_STATIC_TRANS           316
#define IDC_ITALIC                      317
#define IDC_LANG_STATIC_TRANS2          317
#define IDC_UNDERLINE                   318
#define IDB_FILL_COLOR                  318
#define IDC_RETRIEVE_EDIT_RECORD        319
#define IDC_WHOLE_WORDS_CHECK           320
#define IDC_COMBO                       321
#define IDC_FIND_BOX                    322
#define IDS_DELETE_RECORD               323
#define IDC_REPLACE_BOX                 324
#define IDC_SOURCE_CONCORDANCE_SEL      325
#define IDC_TRANS_CONCORDANCE_SEL       326
#define IDS_ADD_GLOSS_ENTRY             327
#define IDS_SAVING_RECORDS              328
#define IDS_SAVED_RECORDS               329
#define IDS_CLEARED_MEMORY              330
#define IDS_MEMORY_CLEARED              331
#define IDS_GLOSSARY_CLEARED            332
#define IDS_SELECT_IMPORT_FILE          333
#define IDS_IMPORT_TRADOS_MEMORY        334
#define IDS_IMPORTING_FILE              335
#define IDS_IMPORT_FAILED               336
#define IDS_IMPORT_ABORTED              337
#define IDS_PROMPT_WRITE_FAILED         338
#define IDS_EXPORTED_RECORDS            339
#define IDS_SAVE_FAILED                 340
#define IDS_EDIT                        341
#define IDS_DELETE                      342
#define IDS_NEW                         343
#define IDS_OPENING_PAGE                344
#define IDS_ADDED_TRANSLATION           345
#define IDS_VALIDATED_TITLE             346
#define IDS_RELIABILITY_TITLE           347
#define IDS_CREATED_TITLE               348
#define IDS_MODIFIED_TITLE              349
#define IDS_NO_MATCHES                  350
#define IDS_SCORE                       351
#define IDS_RICH_QUERY_TITLE            352
#define IDS_RICH_SOURCE_TITLE           353
#define IDS_GLOSS_SOURCE_TMP_ID         354
#define IDS_GLOSS_TRANS_TMP_ID          355
#define IDS_TRANSLATION                 356
#define IDS_BUILD_GLOSS_ENTRY           357
#define IDS_GLOSS_SOURCE_TITLE          358
#define IDS_GLOSS_TRANS_TITLE           359
#define IDS_GLOSS_SOURCE_ID             360
#define IDS_GLOSS_TRANS_ID              361
#define IDS_CANNOT_REGISTER_IN_THIS_STATE 362
#define IDS_GLOSS_TRANSLATION           363
#define IDS_SAVE                        364
#define IDS_TRANS_OR_SOURCE_EMPTY       365
#define IDS_DEMO_LIMIT                  366
#define IDS_PROMPT_PURGE_NONPRINT       367
#define IDS_MSG_XML_LOAD_FAILED         368
#define IDS_PROMPT_SKIP_CURRENT         369
#define IDS_RECORD                      370
#define IDS_PROMPT_SKIP_OR_EDIT_XML     371
#define IDS_MSG_NODE_LOAD_FAILED        372
#define IDS_MSG_MEM_LOAD_ABORTED        373
#define IDS_PROMPT_SAVE_MODIFIED        374
#define IDS_SAVE_FILE_TITLE             375
#define IDS_MSG_FAILED_TO_LOAD_NODE_TAG 376
#define IDS_SAVE_ABORTED                377
#define IDS_FILE_NOT_OPEN_FOR_WRITING   378
#define IDS_MSG_WRITE_FAILED            379
#define IDS_MSG_UNEXPECTED_EOF          380
#define IDS_PROMPT_DISCARD_ENTRY        381
#define IDS_MSG_PARSE_FAILED            382
#define IDS_PROMPT_DEFAULT_FONT_TABLE   383
#define IDS_NO_FONT_TABLE               384
#define IDS_ENTRY_EXISTED               385
#define IDS_NO_QUERIES                  386
#define IDS_EMPTY_TRANSLATION           387
#define IDS_TRANS_SET_FAILED            388
#define IDS_EMPTY_QUERY                 389
#define IDS_INVALID_ACTION              390
#define IDS_FOUND_X_MATCHES_FOR_STRING  391
#define IDS_SHOW_FAILED                 392
#define IDS_SOURCE_SELECTED             393
#define IDS_TRANS_SELECTED              394
#define IDS_INVALID_STATE               395
#define IDS_MEMORY_OPEN                 396
#define IDS_PROMPT_REPLACE_OR_MERGE     397
#define IDS_LOADED_X_RECORDS            398
#define IDS_PREFS_REGISTERED            399
#define IDS_ADD_ENTRY                   400
#define IDS_GLOSSARY_PAGE               401
#define IDS_CHANGED_LANGUAGES           402
#define IDS_PROMPT_DISCARD_LOAD         403
#define IDS_LOAD_RECORD_FAILED          404
#define IDS_DEMO_VER                    405
#define IDS_DEFAULT_ID                  406
#define IDS_USERNAME                    407
#define IDS_USERKEY                     408
#define IDS_REGISTERED_USER             409
#define IDS_REGISTERED_USER_TITLE       410
#define IDS_NOT_REGISTERED_USER         411
#define IDS_NOT_REGISTERED_USER_TITLE   412
#define IDS_KEY_INCORRECT               413
#define IDS_KEY_INCORRECT_TITLE         414
#define IDS_HELPFILE_NAME               415
#define IDS_SEARCH_ALL                  416
#define IDS_SEARCH_SOURCE               417
#define IDS_SEARCH_TRANS                418
#define IDS_SEARCH_CONTEXT              419
#define IDS_RICHEDIT_CREATE_FAILED      420
#define IDS_MADE_REPLACEMENTS           421
#define IDS_MADE_REPLACEMENTS_TITLE     422
#define IDS_SET_LIB_FAILED              423
#define IDC_PREV_MATCH                  424
#define IDS_CORRECTED_TRANS             425
#define IDC_NEXT_MATCH                  426
#define IDS_SHOW_REPORT_FAILED          427
#define IDS_TRANS_LOOKUP_FAILED         428
#define IDS_FAQ_PATH                    430
#define IDS_REFCOUNT_TITLE              431
#define IDS_REFCOUNT_ID                 432
#define IDS_GLOSSARY_OPEN               433
#define IDS_PROMPT_REPLACE_OR_MERGE_GLOSSARY 434
#define IDS_MSG_NO_EMPTY_S_OR_T_GLOSS   435
#define IDS_MEMORY_ID                   436
#define IDS_CANCELLED_ACTION            437
#define IDS_FILE_NAME                   438
#define IDS_CREATOR                     439
#define IDS_FIELD                       440
#define IDS_SOURCE_LANGUAGE             441
#define IDS_TARGET_LANGUAGE             442
#define IDS_CLIENT                      443
#define IDS_NUM_ENTRIES                 444
#define IDS_FILE_SIZE                   445
#define IDS_LOCKED                      446
#define IDS_ADVANCED                    447
#define IDS_EDITOR_TAB                  448
#define IDS_SOURCE_TAB                  449
#define IDS_MEMORY_LOCKED               450
#define IDS_GLOSSARY_LOCKED             451
#define IDS_SETTING_PREFS               452
#define IDS_MSG_NO_EMPTY_S              453
#define IDS_MSG_NO_EMPTY_T              454
#define IDS_MSG_NO_EMPTY_S_GLOSS        455
#define IDS_MSG_NO_EMPTY_T_GLOSS        456
#define IDS_EDIT_TITLE                  457
#define IDS_IMPORTING_RECORD            458
#define IDS_DONE_LOADING                459
#define IDS_DONE_WRITING                460
#define IDS_BATCH_RELIABILITY           461
#define IDC_LOAD_GLOSS                  462
#define IDC_REC_TRANS_STATIC            462
#define IDC_LOAD_MEMS                   463
#define IDC_GLOSS_TRANS_STATIC          463
#define IDC_GLOSS_NAME_COMBO            463
#define IDC_WIZ_GLOSS_REG               464
#define IDC_REC_SOURCE_STATIC           464
#define IDC_TRANS_GLOSS_BOX             464
#define IDC_GLOSS_SOURCE_STATIC         465
#define IDC_SOURCE_GLOSS_BOX            465
#define IDR_HTML1                       465
#define IDC_FUZZY_MATCH_STATIC          466
#define IDC_ADVANCED                    466
#define IDR_GLOSS_TOOLBAR               467
#define IDC_GLOSS_NUM_0                 468
#define IDB_COPY1                       468
#define IDB_MEMORY_CLOSE                468
#define IDC_GLOSS_NUM_1                 469
#define IDD_PROPPAGE_GLOSSARY           469
#define IDC_PLACE_GLOSS_CHECK           469
#define IDC_PLACE_NUMBERS_CHECK         470
#define IDC_CONN_EDIT                   472
#define IDD_CONNECTION_DLG              472
#define IDC_DUP_MSG                     472
#define IDC_MSG_BOX                     473
#define IDC_MERGE                       473
#define IDD_QUERY_MERGE_DLG             473
#define IDC_SEPARATE                    474
#define IDC_DONT_ASK                    475
#define IDD_ZOOM_DLG                    475
#define IDR_SEARCH_ACCEL                475
#define IDC_ASK_MERGE                   476
#define IDC_SLIDER1                     476
#define IDC_COMBO1                      476
#define IDC_ADD_TO_COMBO                476
#define IDD_EDIT_RECORD_GLOSS           476
#define IDC_USER_NAME                   477
#define IDC_ADD_STATIC                  477
#define IDD_SELECT_LANGS_DLG            477
#define IDC_DEFAULTS_CHECK              478
#define IDC_LANG_SOURCE_COMBO           480
#define IDR_APP                         562
#define IDC_CLOSE                       562
#define IDC_ADD_SOURCE                  563
#define IDC_ADD_TRANS                   564
#define IDR_PARAMETERS                  566
#define IDR_APP2                        567
#define IDR_SEARCHRESULT                569
#define IDR_FELIXMEMDOCUIHANDLER        571
#define IDB_SWITCH_VIEWS                572
#define IDS_POPUP_ADD_TO_MEMORY         573
#define IDS_SAVE_GLOSSARY               574
#define IDS_SAVE_MEMORY                 575
#define IDS_SAVE_ALL_GLOSSARIES         576
#define IDS_SAVE_ALL_MEMORIES           577
#define IDR_SEARCHRESULTS               578
#define IDS_SEARCH_MANAGER_TITLE        579
#define IDS_SOURCE_CONCORDANCE			580
#define IDS_TRANS_CONCORDANCE			581
#define IDS_SAVED_RESULTS				582
#define IDS_ACTION_TRIM_SPACES			583
#define IDS_ACTION_STRIP_TAGS			584
#define IDS_ACTION_UNDO_MSG				585
#define IDS_ACTION_REDO_MSG				586
#define ID_HELP_CHECKUPDATES            32770
#define ID_PANE_1                       32771
#define ID_PANE_2                       32772
#define ID_FORMAT_COLOR                 32773
#define ID_FORMAT_HIGHLIGHT             32774
#define ID_VIEW_GLOSSARY                32775
#define ID_VIEW_MEMORY                  32776
#define ID_FORMAT_BOLD                  32777
#define ID_FORMAT_ITALIC                32778
#define ID_FORMAT_UNDERLINE             32779
#define ID_TOOLS_MEMORY_MGR             32780
#define ID_FORMAT_LEFT                  32781
#define ID_FORMAT_CNT                   32782
#define ID_FORMAT_RIGHT                 32783
#define ID_INSERT_UNORD_LIST            32784
#define ID_INSERT_ORD_LIST              32785
#define ID_BUTTON32787                  32786
#define IDS_NEW_TOOLBAR                 32786
#define ID_INSERT_TABLE                 32787
#define ID_EDIT_DELETE                  32788
#define ID_MENUITEM32797                32789
#define ID_GLOSSARY_NEW                 32790
#define ID_FILE_IMPORT                  32791
#define ID_FILE_EXPORT                  32792
#define ID_FILE_EXPORT_MULTITERM        32793
#define ID_EDIT_ADD                     32794
#define ID_VIEW_EDIT_MODE               32795
#define ID_TOOLS_PREFERENCES            32796
#define ID_FILE_IMPORT_MULTITERM        32797
#define ID_TOOLS_LANGUAGE               32798
#define ID_USER_SEARCH                  32799
#define ID_FORMAT_BGCOLOR               32800
#define ID_VIEW_MATCH                   32801
#define ID_VIEW_SEARCH                  32802
#define ID_HELP_REGISTER                32804
#define ID_HELP_TUTORIAL                32805
#define ID_HELP_FAQ                     32806
#define ID_FILE_SAVE_ALL                32807
#define ID_INSERT_SYMBOL                32808
#define ID_VIEW_SWITCH                  32809
#define ID_FORMAT_INDENT                32810
#define ID_FORMAT_OUTDENT               32811
#define ID_UNIT_TEST                    32812
#define ID_FILE_CONNECT                 32814
#define ID_VIEW_ZOOM                    32815
#define ID_TOOLS_LOADPREFERENCES        32816
#define ID_TOOLS_SAVEPREFERENCES        32817
#define IDC_TEST_EXCEPTION              32818
#define ID_FIND_QUICKSEARCH             32820
#define ID_EDIT_REGISTER                32822
#define ID_MEMORY_CLOSE                 32824
#define IDS_MEMORY_CLOSE                32825
#define ID_NEW_SEARCH                   32825
#define IDS_GLOSSARY_CLOSE              32826
#define ID_REPLACE                      32826
#define IDS_CLOSED_MEMORY               32827
#define ID_SEARCH                       32827
#define IDS_CLOSED_GLOSSARY             32828
#define ID_TOGGLE_HELP                  32828
#define IDC_SOURCE_LANG_STATIC          -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
