#ifndef EASYSTL_H
#define EASYSTL_H

// AlgorithmX.h
// Functions that do the same as their STL equivalents,
// but they eliminate iterators from their calls for 
// simplification.

// Author: Brandon Corfman, 7/23/02

#include "algorithmc.h"
#include "algorithmx.h"
#include "listx.h"
#include "vectorx.h"
#include "stringx.h"
#include "mapsetx.h"
#include "overloads.h"

#endif
