/*!
	@file DumpExceptionInfo.h
	@brief dump information from structured windows exceptions to file
	@date 2005/06/25
	Time: 15:17:33
	@author Ryan Ginstrom
	@dir c:\Programming\MyLibrary
 */

#pragma once

#include "File.h"			// file::file

// Disable warnings generated by the Windows header files.
#pragma warning(disable : 4514)
#pragma warning(disable : 4201)

#define _WIN32_WINDOWS 0x0500	// for IsDebuggerPresent

#ifndef _countof
#define _countof(array) (sizeof(array)/sizeof(array[0]))
#endif

#define NumCodeBytes  16	// Number of code bytes to record.
#define MaxStackDump  3072	// Maximum number of DWORDS in stack dumps.
#define StackColumns  4		// Number of columns in stack dump.

#define	ONEK			1024
#define	SIXTYFOURK		(64*ONEK)
#define	ONEM			(ONEK*ONEK)
#define	ONEG			(ONEK*ONEK*ONEK)

bool RecordExceptionInfo(PEXCEPTION_POINTERS pExceptPtrs, LPCSTR lpszMessage) ;
void DumpRegisters(HANDLE LogFile, PCONTEXT Context) ;
void DumpStack(file::file &log_file, DWORD *pStack) ;
string GetExceptionDescription(DWORD ExceptionCode)	;
void DumpSystemInformation(file::file &log_file);
void DumpModuleList(file::file &log_file)  ;
bool DumpModuleInfo(file::file &log_file, HINSTANCE ModuleHandle, int nModuleNo)	   ;
void FormatTime(LPTSTR output, FILETIME TimeToPrint)	 ;

#pragma warning(default : 4201)
