//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AddIn.rc
//
#define IDS_PROJNAME                    100
#define IDR_ADDIN                       101
#define IDS_USER_PREFERENCES            101
#define IDR_CONNECT                     102
#define IDS_USER_PREFERENCES_J          102
#define IDS_LANG_CODE                   105
#define IDC_INPUT_EDIT                  201
#define IDC_SEG_END_EDIT                201
#define IDC_GUI_LANG_BOX                201
#define IDD_NAV_QUERY_DLG               201
#define IDB_LOOKUP_NEXT                 202
#define IDC_LANG_ENG                    202
#define IDC_SKIP_HASJ                   202
#define IDB_LOOKUP                      203
#define IDC_SKIP_NOJ                    203
#define IDC_NAV_BOX                     203
#define IDB_GET                         204
#define IDC_NOSKIP                      204
#define IDD_ADD_GLOSS_J_DLG             204
#define IDB_GET_AND_NEXT                205
#define IDC_SKIP_NUMS_CHECK             205
#define IDC_RADIO2                      205
#define IDB_SET                         206
#define IDC_LANG_JAPANESE               206
#define IDC_SELECT_SPACES               206
#define IDC_FONT_COLOR                  206
#define IDC_SOURCE_EDIT                 206
#define IDD_INPUT_BOX                   207
#define IDC_FONT_BOLD                   207
#define IDC_NAV_ASK                     207
#define IDC_NEXT_SLIDE                  207
#define IDC_TRANS_EDIT                  207
#define IDC_ABBREVIATIONS               207
#define IDB_SET_AND_NEXT                208
#define IDC_FONT_ITALIC                 208
#define IDC_NAV_TOP                     208
#define IDC_SLIDE_TOP                   208
#define IDB_GLOSS_N                     209
#define IDC_FONT_UNDERLINE              209
#define IDC_NAV_SLIDE                   209
#define IDC_DONT_ASK                    209
#define IDS_DELIMITERS                  210
#define IDC_BUTTON1                     210
#define IDC_KEYBOARD_SHORTCUTS          210
#define IDB_SAVE                        211
#define IDS_REG_KEY                     212
#define IDB_CORRECT_AND_NEXT            213
#define IDB_LOOKUP_TRANS                214
#define IDB_CORRECT                     215
#define IDB_WORD                        216
#define IDD_PROPSHEET_E                 216
#define IDB_RESTORE_AND_NEXT            217
#define IDD_PROPPAGE_VIEW_E             217
#define IDB_HELP                        218
#define IDD_PROPPAGE_FORMAT_E           218
#define IDB_RESTORE                     219
#define IDD_PROPPAGE_VIEW_J             219
#define IDB_ALIGN                       220
#define IDD_PROPPAGE_FORMAT_J           220
#define IDB_LOOKUP_NEXT_TRANS           221
#define IDD_PROPSHEET_J                 221
#define IDB_SWITCH_TO_TRANS             222
#define IDD_PROPPAGE_SEGMENTATION_E     222
#define IDB_PROPERTIES                  223
#define IDD_PROPPAGE_SEGMENTATION_J     223
#define IDB_DELETE                      224
#define IDD_NAV_QUERY_DLG_E             224
#define IDB_SWITCH_TO_REVIEW            225
#define IDB_HELP1                       226
#define IDD_ADD_GLOSS_E_DLG             226
#define IDS_AUTO_TRANS_SEL_J            227
#define IDS_AUTO_TRANS_FUZZY_J          228
#define IDS_LOOKUP_J                    229
#define IDS_LOOKUP_NEXT_J               230
#define IDS_CONCORDANCE_J               231
#define IDS_GET_J                       232
#define IDS_GET_AND_NEXT_J              233
#define IDS_SET_J                       234
#define IDS_SET_AND_NEXT_J              235
#define IDS_EXTEND_LOOKUP_J             236
#define IDS_REGISTER_GLOSS_J            237
#define IDS_DELETE_J                    238
#define IDS_NEXT_J                      239
#define IDS_PREV_J                      240
#define IDS_ENTRY_0_J                   241
#define IDS_ENTRY_1_J                   242
#define IDS_ENTRY_2_J                   250
#define IDS_ENTRY_3_J                   251
#define IDS_ENTRY_4_J                   252
#define IDS_ENTRY_5_J                   253
#define IDS_ENTRY_6_J                   254
#define IDS_ENTRY_7_J                   255
#define IDS_ENTRY_8_J                   256
#define IDS_ENTRY_9_J                   257
#define IDS_GLOSS_N_J                   258
#define IDS_LOOKUP_TRANS_J              259
#define IDS_LOOKUP_NEXT_TRANS_J         260
#define IDS_TRANS_CONCORDANCE_J         270
#define IDS_CORRECT_TRANS_J             271
#define IDS_EXTEND_LOOKUP_TRANS_J       272
#define IDS_SAVE_J                      273
#define IDS_ALIGN_J                     274
#define IDS_HELP_J                      275
#define IDS_MENU_GUI_J                  276
#define IDS_GLOSS_POPUP_J               277
#define IDS_ALIGN_WARNING_E             278
#define IDS_ALIGN_WARNING_J             279
#define IDS_OPEN_TRANS_E                280
#define IDS_OPEN_TRANS_J                288
#define IDS_UNKNOWN_SHAPE_TYPE_E        289
#define IDS_UNKNOWN_SHAPE_TYPE_J        290
#define IDB_HELP_IMG                    501
#define IDB_LOOKUP_IMG                  502
#define IDB_GET_IMG                     503
#define IDB_GET_AND_NEXT_IMG            504
#define IDB_SET_IMG                     505
#define IDB_SET_AND_NEXT_IMG            506
#define IDB_GLOSS_N_IMG                 507
#define IDB_SAVE_IMG                    508
#define IDB_LOOKUP_NEXT_IMG             509
#define IDB_CORRECT_AND_NEXT_IMG        510
#define IDB_LOOKUP_TRANS_IMG            511
#define IDB_CORRECT_IMG                 512
#define IDB_RESTORE_AND_NEXT_IMG        513
#define IDB_RESTORE_IMG                 514
#define IDB_LOOKUP_NEXT_TRANS_IMG       515
#define IDB_SWITCH_TO_TRANS_IMG         516
#define IDB_SWITCH_TO_REVIEW_IMG        519

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         211
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
