//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AddIn.rc
//
#define IDS_PROJNAME                    100
#define IDR_ADDIN                       101
#define IDS_MENU_ANALYZE                101
#define IDR_CONNECT                     102
#define IDS_MENU_ANALYZE_DESC           102
#define IDS_CANCEL_J                    103
#define IDS_INPUT_NUM_J                 104
#define IDR_WORD2HTMLPARSER             105
#define IDS_LANG_CODE                   105
#define IDB_HELP                        201
#define IDC_INPUT_EDIT                  201
#define IDD_CONTEXT_ANCHOR              201
#define IDC_SEG_END_EDIT                201
#define IDB_LOOKUP                      202
#define IDC_LANG_ENG                    202
#define IDR_CONTEXT_MENU                202
#define IDC_SKIP_HASJ                   202
#define IDR_IMAGE2                      202
#define IDC_USE_TRANS_HIST              202
#define IDB_GET                         203
#define IDD_INPUT_NUM_DLG               203
#define IDR_CTL_CONTEXT_MENU            203
#define IDC_SKIP_NOJ                    203
#define IDB_GET_AND_NEXT                204
#define IDC_CLASSIC_INTERFACE           204
#define IDR_CONTEXT_MENU_J              204
#define IDC_NOSKIP                      204
#define IDD_ADD_GLOSS_DLG_E2            204
#define IDD_ADD_GLOSS_J_DLG             204
#define IDB_SET                         205
#define IDC_FONT_FACE                   205
#define IDR_CTL_CONTEXT_MENU_J          205
#define IDC_CHECK1                      205
#define IDC_SKIP_NUMS_CHECK             205
#define IDB_SET_AND_NEXT                206
#define IDC_LANG_JAPANESE               206
#define IDC_FONT_COLOR                  206
#define IDC_SELECT_SPACES               206
#define IDC_SOURCE_EDIT                 206
#define IDB_GLOSS_N                     207
#define IDC_RADIO_WORD_DOC              207
#define IDC_FONT_BOLD                   207
#define IDC_TRANS_EDIT                  207
#define IDC_ABBREVIATIONS               207
#define IDB_SAVE                        208
#define IDC_RADIO_HTML_DOC              208
#define IDC_FONT_ITALIC                 208
#define IDB_LOOKUP_NEXT                 209
#define IDC_RADIO_CUSTOM_RULES          209
#define IDC_FONT_UNDERLINE              209
#define IDB_CORRECT_AND_NEXT            210
#define IDC_FONT_SUPER_SUB              210
#define IDC_KEYBOARD_SHORTCUTS          210
#define IDB_LOOKUP_TRANS                211
#define IDC_BUTTON_ADVANCED             211
#define IDB_CORRECT                     212
#define IDB_RESTORE_AND_NEXT            213
#define IDB_RESTORE                     214
#define IDB_LOOKUP_NEXT_TRANS           215
#define IDB_SWITCH_TO_TRANS             216
#define IDD_PROPSHEET_E                 216
#define IDB_PROPERTIES                  217
#define IDD_PROPPAGE_VIEW_E             217
#define IDB_DELETE                      218
#define IDD_PROPPAGE_FORMAT_E           218
#define IDB_SWITCH_TO_REVIEW            219
#define IDD_PROPPAGE_VIEW_J             219
#define IDD_PROPPAGE_FORMAT_J           220
#define IDD_PROPSHEET_J                 221
#define IDD_PROPPAGE_SEGMENTATION_E     222
#define IDD_PROPPAGE_SEGMENTATION_J     223
#define IDD_PROPPAGE_TRANS_HIST_E       224
#define IDD_PROPPAGE_TRANS_HIST_J       225
#define IDD_ADD_GLOSS_E_DLG             226
#define IDS_MENU_ENGLISH_FIRST          301
#define IDS_MENU_AUTO_TRANS_SEL         301
#define IDS_MENU_AUTO_TRANS_SEL_TT      302
#define IDS_MENU_AUTO_TRANS_FUZZY       303
#define IDS_MENU_AUTO_TRANS_FUZZY_TT    304
#define IDS_MENU_LOOKUP_NEXT            305
#define IDS_MENU_LOOKUP_NEXT_TT         306
#define IDS_MENU_LOOKUP                 307
#define IDS_MENU_LOOKUP_TT              308
#define IDS_MENU_EXTEND                 309
#define IDS_MENU_EXTEND_TT              310
#define IDS_MENU_REGISTER               311
#define IDS_MENU_REGISTER_TT            312
#define IDS_MENU_REGISTER_GLOSS         313
#define IDS_MENU_REGISTER_GLOSS_TT      314
#define IDS_MENU_SET_AND_NEXT           315
#define IDS_MENU_SET_AND_NEXT_TT        316
#define IDS_MENU_GET                    317
#define IDS_MENU_GET_TT                 318
#define IDS_MENU_GET_AND_NEXT           319
#define IDS_MENU_GET_AND_NEXT_TT        320
#define IDS_MENU_GET_GLOSS              321
#define IDS_MENU_GET_GLOSS_TT           322
#define IDS_MENU_ENTRY_0                323
#define IDS_MENU_ENTRY_0_TT             324
#define IDS_MENU_ENTRY_1                325
#define IDS_MENU_ENTRY_1_TT             326
#define IDS_MENU_ENTRY_2                327
#define IDS_MENU_ENTRY_2_TT             328
#define IDS_MENU_ENTRY_3                329
#define IDS_MENU_ENTRY_3_TT             330
#define IDS_MENU_ENTRY_4                331
#define IDS_MENU_ENTRY_4_TT             332
#define IDS_MENU_ENTRY_5                333
#define IDS_MENU_ENTRY_5_TT             334
#define IDS_MENU_ENTRY_6                335
#define IDS_MENU_ENTRY_6_TT             336
#define IDS_MENU_ENTRY_7                337
#define IDS_MENU_ENTRY_7_TT             338
#define IDS_MENU_ENTRY_8                339
#define IDS_MENU_ENTRY_8_TT             340
#define IDS_MENU_ENTRY_9                341
#define IDS_MENU_ENTRY_9_TT             342
#define IDS_MENU_GLOSS_N                343
#define IDS_MENU_GLOSS_N_TT             344
#define IDS_MENU_DELETE                 345
#define IDS_MENU_DELETE_TT              346
#define IDS_MENU_NEXT                   347
#define IDS_MENU_NEXT_TT                348
#define IDS_MENU_PREV                   349
#define IDS_MENU_PREV_TT                350
#define IDS_MENU_CONCORDANCE            351
#define IDS_MENU_CONCORDANCE_TT         352
#define IDS_MENU_LOOKUP_TRANS           353
#define IDS_MENU_LOOKUP_TRANS_TT        354
#define IDS_MENU_LOOKUP_NEXT_TRANS      355
#define IDS_MENU_LOOKUP_NEXT_TRANS_TT   356
#define IDS_MENU_CONCORDANCE_TRANS      357
#define IDS_MENU_CONCORDANCE_TRANS_TT   358
#define IDS_MENU_EXTEND_TRANS           359
#define IDS_MENU_EXTEND_TRANS_TT        360
#define IDS_MENU_CORRECT_TRANS          361
#define IDS_MENU_CORRECT_TRANS_TT       362
#define IDS_MENU_SAVE                   363
#define IDS_MENU_SAVE_TT                364
#define IDS_MENU_GUI                    365
#define IDS_MENU_GUI_TT                 366
#define IDS_MENU_HELP                   367
#define IDS_MENU_HELP_TT                368
#define IDS_MENU_CORRECT_AND_NEXT       369
#define IDS_MENU_CORRECT_AND_NEXT_TT    370
#define IDS_MENU_RESTORE                371
#define IDS_MENU_RESTORE_TT             372
#define IDS_MENU_RESTORE_AND_NEXT       373
#define IDS_MENU_RESTORE_AND_NEXT_TT    374
#define IDS_MENU_PREFERENCES            375
#define IDS_MENU_PREFERENCES_TT         376
#define IDS_MENU_TO_TRANS_MODE          377
#define IDS_MENU_TO_TRANS_MODE_TT       378
#define IDS_MENU_TO_REVIEW_MODE         379
#define IDS_MENU_TO_REVIEW_MODE_TT      380
#define IDS_MENU_MEMORY_TO_TRANS        381
#define IDS_MENU_MEMORY_TO_TRANS_TT     382
#define IDS_MENU_TRANS_TO_MEMORY        383
#define IDS_MENU_TRANS_TO_MEMORY_TT     384
#define IDS_MENU_JAPANESE_FIRST         401
#define IDS_MENU_AUTO_TRANS_SEL_J       401
#define IDS_MENU_AUTO_TRANS_SEL_TT_J    402
#define IDS_MENU_AUTO_TRANS_FUZZY_J     403
#define IDS_MENU_AUTO_TRANS_FUZZY_TT_J  404
#define IDS_MENU_LOOKUP_NEXT_J          405
#define IDS_MENU_LOOKUP_NEXT_TT_J       406
#define IDS_MENU_LOOKUP_J               407
#define IDS_MENU_LOOKUP_TT_J            408
#define IDS_MENU_EXTEND_J               409
#define IDS_MENU_EXTEND_TT_J            410
#define IDS_MENU_REGISTER_J             411
#define IDS_MENU_REGISTER_TT_J          412
#define IDS_MENU_REGISTER_GLOSS_J       413
#define IDS_MENU_REGISTER_GLOSS_TT_J    414
#define IDS_MENU_SET_AND_NEXT_J         415
#define IDS_MENU_SET_AND_NEXT_TT_J      416
#define IDS_MENU_GET_J                  417
#define IDS_MENU_GET_TT_J               418
#define IDS_MENU_GET_AND_NEXT_J         419
#define IDS_MENU_GET_AND_NEXT_TT_J      420
#define IDS_MENU_GET_GLOSS_J            421
#define IDS_MENU_GET_GLOSS_TT_J         422
#define IDS_MENU_ENTRY_0_J              423
#define IDS_MENU_ENTRY_0_TT_J           424
#define IDS_MENU_ENTRY_1_J              425
#define IDS_MENU_ENTRY_1_TT_J           426
#define IDS_MENU_ENTRY_2_J              427
#define IDS_MENU_ENTRY_2_TT_J           428
#define IDS_MENU_ENTRY_3_J              429
#define IDS_MENU_ENTRY_3_TT_J           430
#define IDS_MENU_ENTRY_4_J              431
#define IDS_MENU_ENTRY_4_TT_J           432
#define IDS_MENU_ENTRY_5_J              433
#define IDS_MENU_ENTRY_5_TT_J           434
#define IDS_MENU_ENTRY_6_J              435
#define IDS_MENU_ENTRY_6_TT_J           436
#define IDS_MENU_ENTRY_7_J              437
#define IDS_MENU_ENTRY_7_TT_J           438
#define IDS_MENU_ENTRY_8_J              439
#define IDS_MENU_ENTRY_8_TT_J           440
#define IDS_MENU_ENTRY_9_J              441
#define IDS_MENU_ENTRY_9_TT_J           442
#define IDS_MENU_GLOSS_N_J              443
#define IDS_MENU_GLOSS_N_TT_J           444
#define IDS_MENU_DELETE_J               445
#define IDS_MENU_DELETE_TT_J            446
#define IDS_MENU_NEXT_J                 447
#define IDS_MENU_NEXT_TT_J              448
#define IDS_MENU_PREV_J                 449
#define IDS_MENU_PREV_TT_J              450
#define IDS_MENU_CONCORDANCE_J          451
#define IDS_MENU_CONCORDANCE_TT_J       452
#define IDS_MENU_LOOKUP_TRANS_J         453
#define IDS_MENU_LOOKUP_TRANS_TT_J      454
#define IDS_MENU_LOOKUP_NEXT_TRANS_J    455
#define IDS_MENU_LOOKUP_NEXT_TRANS_TT_J 456
#define IDS_MENU_CONCORDANCE_TRANS_J    457
#define IDS_MENU_CONCORDANCE_TRANS_TT_J 458
#define IDS_MENU_EXTEND_TRANS_J         459
#define IDS_MENU_EXTEND_TRANS_TT_J      460
#define IDS_MENU_CORRECT_TRANS_J        461
#define IDS_MENU_CORRECT_TRANS_TT_J     462
#define IDS_MENU_SAVE_J                 463
#define IDS_MENU_SAVE_TT_J              464
#define IDS_MENU_GUI_J                  465
#define IDS_MENU_GUI_TT_J               466
#define IDS_MENU_HELP_J                 467
#define IDS_MENU_HELP_TT_J              468
#define IDS_MENU_CORRECT_AND_NEXT_J     469
#define IDS_MENU_CORRECT_AND_NEXT_TT_J  470
#define IDS_MENU_RESTORE_J              471
#define IDS_MENU_RESTORE_TT_J           472
#define IDS_MENU_RESTORE_AND_NEXT_J     473
#define IDS_MENU_RESTORE_AND_NEXT_TT_J  474
#define IDS_MENU_PREFERENCES_J          475
#define IDS_MENU_PREFERENCES_TT_J       476
#define IDS_MENU_TO_TRANS_MODE_J        477
#define IDS_MENU_TO_TRANS_MODE_TT_J     478
#define IDS_MENU_TO_REVIEW_MODE_J       479
#define IDS_MENU_TO_REVIEW_MODE_TT_J    480
#define IDS_MENU_MEMORY_TO_TRANS_J      481
#define IDS_MENU_MEMORY_TO_TRANS_TT_J   482
#define IDS_MENU_TRANS_TO_MEMORY_J      483
#define IDS_MENU_TRANS_TO_MEMORY_TT_J   484
#define IDB_HELP_IMG                    501
#define IDB_LOOKUP_IMG                  502
#define IDB_GET_IMG                     503
#define IDB_GET_AND_NEXT_IMG            504
#define IDB_SET_IMG                     505
#define IDB_SET_AND_NEXT_IMG            506
#define IDB_GLOSS_N_IMG                 507
#define IDB_SAVE_IMG                    508
#define IDB_LOOKUP_NEXT_IMG             509
#define IDB_CORRECT_AND_NEXT_IMG        510
#define IDB_LOOKUP_TRANS_IMG            511
#define IDB_CORRECT_IMG                 512
#define IDB_RESTORE_AND_NEXT_IMG        513
#define IDB_RESTORE_IMG                 514
#define IDB_LOOKUP_NEXT_TRANS_IMG       515
#define IDB_SWITCH_TO_TRANS_IMG         516
#define IDB_PROPERTIES_IMG              517
#define IDB_DELETE_IMG                  518
#define IDB_SWITCH_TO_REVIEW_IMG        519
#define IDS_CLASSIC_MENU_ENGLISH_FIRST  601
#define IDS_CLASSIC_MENU_AUTO_TRANS_SEL 601
#define IDS_CLASSIC_MENU_AUTO_TRANS_SEL_TT 602
#define IDS_CLASSIC_MENU_AUTO_TRANS_FUZZY 603
#define IDS_CLASSIC_MENU_AUTO_TRANS_FUZZY_TT 604
#define IDS_CLASSIC_MENU_LOOKUP_NEXT    605
#define IDS_CLASSIC_MENU_LOOKUP_NEXT_TT 606
#define IDS_CLASSIC_MENU_LOOKUP         607
#define IDS_CLASSIC_MENU_LOOKUP_TT      608
#define IDS_CLASSIC_MENU_EXTEND         609
#define IDS_CLASSIC_MENU_EXTEND_TT      610
#define IDS_CLASSIC_MENU_REGISTER       611
#define IDS_CLASSIC_MENU_REGISTER_TT    612
#define IDS_CLASSIC_MENU_REGISTER_GLOSS 613
#define IDS_CLASSIC_MENU_REGISTER_GLOSS_TT 614
#define IDS_CLASSIC_MENU_SET_AND_NEXT   615
#define IDS_CLASSIC_MENU_SET_AND_NEXT_TT 616
#define IDS_CLASSIC_MENU_GET            617
#define IDS_CLASSIC_MENU_GET_TT         618
#define IDS_CLASSIC_MENU_GET_AND_NEXT   619
#define IDS_CLASSIC_MENU_GET_AND_NEXT_TT 620
#define IDS_CLASSIC_MENU_GET_GLOSS      621
#define IDS_CLASSIC_MENU_GET_GLOSS_TT   622
#define IDS_CLASSIC_MENU_ENTRY_0        623
#define IDS_CLASSIC_MENU_ENTRY_0_TT     624
#define IDS_CLASSIC_MENU_ENTRY_1        625
#define IDS_CLASSIC_MENU_ENTRY_1_TT     626
#define IDS_CLASSIC_MENU_ENTRY_2        627
#define IDS_CLASSIC_MENU_ENTRY_2_TT     628
#define IDS_CLASSIC_MENU_ENTRY_3        629
#define IDS_CLASSIC_MENU_ENTRY_3_TT     630
#define IDS_CLASSIC_MENU_ENTRY_4        631
#define IDS_CLASSIC_MENU_ENTRY_4_TT     632
#define IDS_CLASSIC_MENU_ENTRY_5        633
#define IDS_CLASSIC_MENU_ENTRY_5_TT     634
#define IDS_CLASSIC_MENU_ENTRY_6        635
#define IDS_CLASSIC_MENU_ENTRY_6_TT     636
#define IDS_CLASSIC_MENU_ENTRY_7        637
#define IDS_CLASSIC_MENU_ENTRY_7_TT     638
#define IDS_CLASSIC_MENU_ENTRY_8        639
#define IDS_CLASSIC_MENU_ENTRY_8_TT     640
#define IDS_CLASSIC_MENU_ENTRY_9        641
#define IDS_CLASSIC_MENU_ENTRY_9_TT     642
#define IDS_CLASSIC_MENU_GLOSS_N        643
#define IDS_CLASSIC_MENU_GLOSS_N_TT     644
#define IDS_CLASSIC_MENU_DELETE         645
#define IDS_CLASSIC_MENU_DELETE_TT      646
#define IDS_CLASSIC_MENU_NEXT           647
#define IDS_CLASSIC_MENU_NEXT_TT        648
#define IDS_CLASSIC_MENU_PREV           649
#define IDS_CLASSIC_MENU_PREV_TT        650
#define IDS_CLASSIC_MENU_CONCORDANCE    651
#define IDS_CLASSIC_MENU_CONCORDANCE_TT 652
#define IDS_CLASSIC_MENU_LOOKUP_TRANS   653
#define IDS_CLASSIC_MENU_LOOKUP_TRANS_TT 654
#define IDS_CLASSIC_MENU_LOOKUP_NEXT_TRANS 655
#define IDS_CLASSIC_MENU_LOOKUP_NEXT_TRANS_TT 656
#define IDS_CLASSIC_MENU_CONCORDANCE_TRANS 657
#define IDS_CLASSIC_MENU_CONCORDANCE_TRANS_TT 658
#define IDS_CLASSIC_MENU_EXTEND_TRANS   659
#define IDS_CLASSIC_MENU_EXTEND_TRANS_TT 660
#define IDS_CLASSIC_MENU_CORRECT_TRANS  661
#define IDS_CLASSIC_MENU_CORRECT_TRANS_TT 662
#define IDS_CLASSIC_MENU_SAVE           663
#define IDS_CLASSIC_MENU_SAVE_TT        664
#define IDS_CLASSIC_MENU_GUI            665
#define IDS_CLASSIC_MENU_GUI_TT         666
#define IDS_CLASSIC_MENU_HELP           667
#define IDS_CLASSIC_MENU_HELP_TT        668
#define IDS_CLASSIC_MENU_CORRECT_AND_NEXT 669
#define IDS_CLASSIC_MENU_CORRECT_AND_NEXT_TT 670
#define IDS_CLASSIC_MENU_RESTORE        671
#define IDS_CLASSIC_MENU_RESTORE_TT     672
#define IDS_CLASSIC_MENU_RESTORE_AND_NEXT 673
#define IDS_CLASSIC_MENU_RESTORE_AND_NEXT_TT 674
#define IDS_CLASSIC_MENU_PREFERENCES    675
#define IDS_CLASSIC_MENU_PREFERENCES_TT 676
#define IDS_CLASSIC_MENU_JAPANESE_FIRST 701
#define IDS_CLASSIC_MENU_AUTO_TRANS_SEL_J 701
#define IDS_CLASSIC_MENU_AUTO_TRANS_SEL_TT_J 702
#define IDS_CLASSIC_MENU_AUTO_TRANS_FUZZY_J 703
#define IDS_CLASSIC_MENU_AUTO_TRANS_FUZZY_TT_J 704
#define IDS_CLASSIC_MENU_LOOKUP_NEXT_J  705
#define IDS_CLASSIC_MENU_LOOKUP_NEXT_TT_J 706
#define IDS_CLASSIC_MENU_LOOKUP_J       707
#define IDS_CLASSIC_MENU_LOOKUP_TT_J    708
#define IDS_CLASSIC_MENU_EXTEND_J       709
#define IDS_CLASSIC_MENU_EXTEND_TT_J    710
#define IDS_CLASSIC_MENU_REGISTER_J     711
#define IDS_CLASSIC_MENU_REGISTER_TT_J  712
#define IDS_CLASSIC_MENU_REGISTER_GLOSS_J 713
#define IDS_CLASSIC_MENU_REGISTER_GLOSS_TT_J 714
#define IDS_CLASSIC_MENU_SET_AND_NEXT_J 715
#define IDS_CLASSIC_MENU_SET_AND_NEXT_TT_J 716
#define IDS_CLASSIC_MENU_GET_J          717
#define IDS_CLASSIC_MENU_GET_TT_J       718
#define IDS_CLASSIC_MENU_GET_AND_NEXT_J 719
#define IDS_CLASSIC_MENU_GET_AND_NEXT_TT_J 720
#define IDS_CLASSIC_MENU_GET_GLOSS_J    721
#define IDS_CLASSIC_MENU_GET_GLOSS_TT_J 722
#define IDS_CLASSIC_MENU_ENTRY_0_J      723
#define IDS_CLASSIC_MENU_ENTRY_0_TT_J   724
#define IDS_CLASSIC_MENU_ENTRY_1_J      725
#define IDS_CLASSIC_MENU_ENTRY_1_TT_J   726
#define IDS_CLASSIC_MENU_ENTRY_2_J      727
#define IDS_CLASSIC_MENU_ENTRY_2_TT_J   728
#define IDS_CLASSIC_MENU_ENTRY_3_J      729
#define IDS_CLASSIC_MENU_ENTRY_3_TT_J   730
#define IDS_CLASSIC_MENU_ENTRY_4_J      731
#define IDS_CLASSIC_MENU_ENTRY_4_TT_J   732
#define IDS_CLASSIC_MENU_ENTRY_5_J      733
#define IDS_CLASSIC_MENU_ENTRY_5_TT_J   734
#define IDS_CLASSIC_MENU_ENTRY_6_J      735
#define IDS_CLASSIC_MENU_ENTRY_6_TT_J   736
#define IDS_CLASSIC_MENU_ENTRY_7_J      737
#define IDS_CLASSIC_MENU_ENTRY_7_TT_J   738
#define IDS_CLASSIC_MENU_ENTRY_8_J      739
#define IDS_CLASSIC_MENU_ENTRY_8_TT_J   740
#define IDS_CLASSIC_MENU_ENTRY_9_J      741
#define IDS_CLASSIC_MENU_ENTRY_9_TT_J   742
#define IDS_CLASSIC_MENU_GLOSS_N_J      743
#define IDS_CLASSIC_MENU_GLOSS_N_TT_J   744
#define IDS_CLASSIC_MENU_DELETE_J       745
#define IDS_CLASSIC_MENU_DELETE_TT_J    746
#define IDS_CLASSIC_MENU_NEXT_J         747
#define IDS_CLASSIC_MENU_NEXT_TT_J      748
#define IDS_CLASSIC_MENU_PREV_J         749
#define IDS_CLASSIC_MENU_PREV_TT_J      750
#define IDS_CLASSIC_MENU_CONCORDANCE_J  751
#define IDS_CLASSIC_MENU_CONCORDANCE_TT_J 752
#define IDS_CLASSIC_MENU_LOOKUP_TRANS_J 753
#define IDS_CLASSIC_MENU_LOOKUP_TRANS_TT_J 754
#define IDS_CLASSIC_MENU_LOOKUP_NEXT_TRANS_J 755
#define IDS_CLASSIC_MENU_LOOKUP_NEXT_TRANS_TT_J 756
#define IDS_CLASSIC_MENU_CONCORDANCE_TRANS_J 757
#define IDS_CLASSIC_MENU_CONCORDANCE_TRANS_TT_J 758
#define IDS_CLASSIC_MENU_EXTEND_TRANS_J 759
#define IDS_CLASSIC_MENU_EXTEND_TRANS_TT_J 760
#define IDS_CLASSIC_MENU_CORRECT_TRANS_J 761
#define IDS_CLASSIC_MENU_CORRECT_TRANS_TT_J 762
#define IDS_CLASSIC_MENU_SAVE_J         763
#define IDS_CLASSIC_MENU_SAVE_TT_J      764
#define IDS_CLASSIC_MENU_GUI_J          765
#define IDS_CLASSIC_MENU_GUI_TT_J       766
#define IDS_CLASSIC_MENU_HELP_J         767
#define IDS_CLASSIC_MENU_HELP_TT_J      768
#define IDS_CLASSIC_MENU_CORRECT_AND_NEXT_J 769
#define IDS_CLASSIC_MENU_CORRECT_AND_NEXT_TT_J 770
#define IDS_CLASSIC_MENU_RESTORE_J      771
#define IDS_CLASSIC_MENU_RESTORE_TT_J   772
#define IDS_CLASSIC_MENU_RESTORE_AND_NEXT_J 773
#define IDS_CLASSIC_MENU_RESTORE_AND_NEXT_TT_J 774
#define IDS_CLASSIC_MENU_PREFERENCES_J  775
#define IDS_CLASSIC_MENU_PREFERENCES_TT_J 776
#define IDS_PROPSHEET_TITLE_E           900
#define IDS_PROPSHEET_TITLE_J           901

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        205
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         209
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
