// This file was generated by WTL Dialog wizard 
// Segmentation.h : Declaration of the CSegmentation

#pragma once

#include "resource.h"       // main symbols
#include <atlddx.h>
#include <atlcrack.h>
// CSegmentation

class CSegmentation : 
	public CDialogImpl<CSegmentation>,
	public CWinDataExchange<CSegmentation>	
{

public:
	CSegmentation(void);
public:
	CString m_strSegEndEdit;BOOL m_bSkipNumsCheck;int m_iSkipHasj;


public:
	CSegmentation()
	{
	}

	~CSegmentation()
	{
	}
	enum { IDD = IDD_PROPPAGE_SEGMENTATION_E };

    BEGIN_MSG_MAP(CSegmentation)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
        COMMAND_HANDLER(IDOK, BN_CLICKED, OnClickedOK)
        COMMAND_HANDLER(IDCANCEL, BN_CLICKED, OnClickedCancel)
		COMMAND_HANDLER_EX(IDC_RADIO_WORD_DOC, BN_CLICKED, OnRadioWordDocBnClicked)
		COMMAND_HANDLER_EX(IDC_RADIO_HTML_DOC, BN_CLICKED, OnRadioHtmlDocBnClicked)
		COMMAND_HANDLER_EX(IDC_RADIO_WORD_DOC, BN_CLICKED, OnRadioWordDocBnClicked)
    END_MSG_MAP()
	LRESULT CSegmentation::OnRadioWordDocBnClicked(WORD wNotifyCode, WORD wID, HWND hWndCtl)
	{

		return 0;
	}

	BEGIN_DDX_MAP(CSegmentation)
		DDX_TEXT(IDC_SEG_END_EDIT, m_strSegEndEdit)
		DDX_CHECK(IDC_SKIP_NUMS_CHECK, m_bSkipNumsCheck)
		DDX_RADIO(IDC_SKIP_HASJ, m_iSkipHasj)
	END_DDX_MAP()
    // Handler prototypes:
    //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
    //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
	{
		DoDataExchange();
		return 1;  // Let the system set the focus
	}

	LRESULT OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
	{
		DoDataExchange(TRUE);
		EndDialog(wID);
		return 0;
	}

	LRESULT OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
	{
		EndDialog(wID);
		return 0;
	}
	LRESULT OnRadioHtmlDocBnClicked(WORD wNotifyCode, WORD wID, HWND hWndCtl);
};


